name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release Extension
    #if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: murar8/gnome-extensions-action@0.1.1
        id: package
      - uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.package.outputs.zip-file }}
      - uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ steps.package.outputs.zip-file }}

